version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 1Us3rP@ss
      MYSQL_DATABASE: banking
      MYSQL_ROOT_PASSWORD: R00tP@ss
      TZ: TZ=America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - /home/bat/work/workspace/mysql3:/var/lib/mysql